MotiaDev/motia

packages/core/src/utils.ts, packages/docs/app/(home)/components/codeExamples.ts, packages/docs/content/docs/concepts/logging-and-debugging.mdx, packages/docs/content/docs/getting-started/quick-start.mdx, packages/docs/public/llms.txt, packages/snap/package.json, packages/snap/src/cli.ts
=> Fix some issues that were released

packages/snap/README.md
Super small, but easy to fix while I'm here.
=> Fix: Update motiajs to MotiaDev

packages/snap/src/generate-types.ts, packages/stream-client-browser/src/stream.ts
* Streams groups were not receiving proper updates
* npx motia generate-types wasn't creating the streams types
=> fix: stream group not receiving proper updates

.gitignore, packages/workbench/src/components/logs/log-console.tsx, packages/workbench/src/routes/flow.tsx, packages/workbench/src/views/flow/hooks/use-get-flow-state.tsx
https://github.com/user-attachments/assets/12cb2275-ed61-4310-8c2d-f897b149a63c
=> fix: handle flow errors and improve log console behavior

.github/workflows/e2e-tests-pr.yml, .gitignore, eslint.config.js, packages/core/src/python/context.py, packages/core/src/python/dot_dict.py, packages/core/src/python/python-runner.py, packages/core/src/python/rpc_stream_manager.py, packages/core/src/server.ts, packages/core/src/socket-server.ts, packages/e2e/scripts/global-setup.ts, packages/snap/src/generate-locked-data.ts, packages/stream-client-browser/.npmignore, packages/stream-client-browser/__tests__/stream-group.spec.ts, packages/stream-client-browser/__tests__/stream-item.spec.ts, packages/stream-client-browser/jest.config.ts, packages/stream-client-browser/package.json, packages/stream-client-browser/src/stream-group.ts, packages/stream-client-browser/src/stream-item.ts, packages/stream-client-browser/src/stream.ts, packages/stream-client-browser/src/stream.types.ts, packages/stream-client-browser/tsconfig.json, packages/stream-client-react/src/use-stream-group.ts, packages/workbench/src/components/endpoints/hooks/use-get-endpoints.ts, playground/motia-workbench.json, playground/requirements.txt, playground/steps/open-ai-python/00-open-ai-message.stream.py, playground/steps/open-ai-python/01-prompt-api.step.py, playground/steps/open-ai-python/02-prompt.step.py, playground/types.d.ts, pnpm-lock.yaml
* Streams now working with Python
* Added sorting key to useStreamGroup hook
* Added unit-tests to motia-streams-browser covering most of the use-cases
https://github.com/user-attachments/assets/23414e54-85d1-4037-b6ab-59be039be4e7
=> feat: introducing streams to python

packages/snap/src/cli.ts, packages/snap/src/create/interactive.ts
https://github.com/user-attachments/assets/52f8da01-d8c2-42cb-bf07-5e7e57a791d0
=> feat: add interactive project creation prompts and refactor CLI options

packages/e2e/tests/page-objects/EnpointPage.ts, packages/e2e/tests/page-objects/index.ts, packages/e2e/tests/workbench/endpoint-call.spec.ts, packages/workbench/src/components/endpoints/endpoint-call.tsx, packages/workbench/src/components/endpoints/endpoints.tsx, playground/motia-workbench.json, playground/types.d.ts, pnpm-lock.yaml
https://linear.app/motia/issue/MOT-330/providing-invalid-json-in-endpoints-ui-breaks
- Introduced `EndpointPage` class for managing endpoint interactions in E2E tests.
- Created `endpoint-call.spec.ts` to validate JSON body input, ensuring proper handling of valid and invalid JSON.
- Updated `endpoint-call.tsx` to include JSON validation logic and UI feedback for invalid input.
- Enhanced `endpoints.tsx` to include data-testid attributes for better test targeting.
- Updated playground configuration to reflect new test structure.
=> feat: add endpoint page object and validation tests for JSON input in workbench

package.json, packages/workbench/jest.config.js, packages/workbench/package.json, packages/workbench/src/components/logs/log-field.test.tsx, packages/workbench/src/components/logs/log-field.tsx, packages/workbench/src/setupTests.ts, packages/workbench/tsconfig.app.json, pnpm-lock.yaml
https://linear.app/motia/issue/MOT-334/cannot-convert-undefined-or-null-to-object-when-opening-log
- Introduced Jest configuration in `jest.config.js` for testing setup.
- Added test scripts in `package.json` for running tests.
- Created `setupTests.ts` to include custom Jest matchers from `@testing-library/jest-dom`.
- Implemented comprehensive tests for `LogField` component covering various value types (string, React nodes, objects, etc.) and edge cases.
=> feat(workbench): add Jest configuration and initial tests for LogField component

packages/docs/components/CopyNpx.tsx
=> Update CopyNpx.tsx to use `motia@latest`

.gitignore, packages/ui/components.json, packages/ui/package.json, packages/ui/src/components/ui/button.stories.tsx, packages/ui/src/components/ui/button.tsx, packages/ui/src/components/ui/input.stories.tsx, packages/ui/src/components/ui/input.tsx, packages/ui/src/components/ui/panel.stories.tsx, packages/ui/src/components/ui/panel.tsx, packages/ui/src/components/ui/textarea.stories.tsx, packages/ui/src/components/ui/textarea.tsx, packages/ui/src/index.ts, packages/ui/src/styles/globals.css, packages/workbench/index.tsx, packages/workbench/package.json, packages/workbench/src/components/endpoints/endpoint-call.tsx, packages/workbench/src/components/logs/log-console.tsx, packages/workbench/src/components/ui/button.tsx, packages/workbench/src/components/ui/sidebar.tsx, packages/workbench/src/index.css, packages/workbench/src/routes/index.tsx, packages/workbench/src/views/flow/legend.tsx, playground/types.d.ts, pnpm-lock.yaml
This PR introduces a comprehensive set of reusable UI components and enhances the Workbench interface with improved styling and component organization. The changes focus on building a solid foundation for consistent UI patterns across the Motia platform.
- **Input Component** (`packages/ui/src/components/ui/input.tsx`)
- Fully accessible input field with comprehensive styling
- Includes extensive Storybook stories for all variations
- Supports various input types and states
- **Panel Component** (`packages/ui/src/components/ui/panel.tsx`)
- Flexible container component for organizing content
- Multiple styling variants and configurations
- Complete Storybook documentation
- **Textarea Component** (`packages/ui/src/components/ui/textarea.tsx`)
- Multi-line text input with consistent …
=> mot-381 - UI Components Enhancement and Workbench Refactoring

packages/workbench/src/components/observability/trace-item/trace-item.tsx, packages/workbench/src/components/observability/trace-timeline.tsx
https://github.com/user-attachments/assets/e8283a24-f652-4856-9db0-156afb78196d
=> fix: fixing traces scrolling and sticky bars

packages/ui/src/components/ui/panel.tsx, packages/workbench/src/components/endpoints/endpoint-badge.tsx, packages/workbench/src/components/endpoints/endpoint-call.tsx, packages/workbench/src/components/endpoints/endpoint-response.tsx, packages/workbench/src/components/endpoints/endpoints.tsx, packages/workbench/src/index.css
=> feat: endpoints redesign second batch

packages/snap/src/create-step/templates/ui/api.step.txt, packages/snap/src/create-step/templates/ui/cron.step.txt, packages/snap/src/create-step/templates/ui/event.step.txt, packages/snap/src/create-step/templates/ui/noop.step.txt, packages/snap/src/create/templates/default/steps/00-noop.step.tsx.txt, packages/snap/src/create/templates/python/steps/00-noop.step.tsx.txt
=> fix: template noop button

packages/ui/src/components/ui/panel.stories.tsx, packages/ui/src/components/ui/panel.tsx, packages/workbench/src/App.tsx, packages/workbench/src/components/flow/flow-tab-menu-item.tsx
=> feat: enhance Panel component with new variants, size options, and tab functionality in stories

packages/snap/src/cloud/build/index.ts
We had a chicken and the egg enigma in the builder process. We were reading the config from all seps to determine if we should active python env, but to read the configs we needed pyenv activated.
This changes the flow, we're checking file names instead
=> fix: build with python and pyenv

packages/workbench/src/components/observability/trace-item/trace-item.tsx, packages/workbench/src/components/observability/trace-timeline.tsx, packages/workbench/src/components/sidebar/sidebar.tsx, playground/types.d.ts
=> refactor: update styles in observability components and sidebar for consistency

packages/core/src/call-step-file.ts, packages/core/src/server.ts, packages/snap/src/dev-watchers.ts
* Added streams data
* Added stepName to execution start
* Added API calls to get the usage there as well
=> chore: adding some analytics data

packages/docker/README.md, packages/docker/templates/MotiaDockerSample, packages/docs/content/docs/concepts/deployment/self-hosted.mdx
- Update references to the sample dockerfiles for motia projects
=> chore: udpate sample dockerfiles for motia projects

packages/docs/content/docs/concepts/deployment/motia-cloud/continuous-deployment.mdx
=> fix: making github link english

packages/core/src/printer.ts
```
Created makes me think that things files are being created
```
=> fix: label renamed from created to registered

README.md
Expanded description of the framework's features.
=> Enhance README with additional features description
